---
title: "Programming Assignment 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1 Plot the 30-day mortality rates for heart attack

```{r}
setwd("/home/duco/dev/R Programming/Programming Assignment 3/")
```

```{r}
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
head(outcome)
```
```{r}
outcome[, 11] <- as.numeric(outcome[, 11])
```

```{r}
hist(outcome[, 11])
```

## 2 Finding the best hospital in a state

```{r}
best <- function(state, outcome) {
## Read outcome data
        outcome.data <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
## Check that state and outcome are valid
        try(if(!state %in% outcome.data$State) stop("invalid state"))
        outcomes <- c("heart attack", "heart failure", "pneumonia")
        try(if(!outcome %in% outcomes) stop("invalid outcome"))
## Return hospital name in that state with lowest 30-day death rate
        # only use data of requested state
        outcome.data.state <- outcome.data[outcome.data$State == state,]
        
        # list indexes of relevent columns of outcomes
        index.list <- c("heart attack" = 11, "heart failure" = 17, "pneumonia" = 23)
        index <- index.list[outcome]
        
        # Transform outcome variable column to numeric
        outcome.data.state[,index] <- as.numeric(outcome.data.state[,index])
        # Find the min value of outcome variable using the min fucntion will return NA,
        # could possibly also solve this by omit.na or similar
        min.value <- sort(outcome.data.state[,index])[1] 
        # Find names of hospital which have this value
        winners = outcome.data.state[outcome.data.state[,index] == min.value, 2]
        # In case of ties, sorting alphabetically and return the first
        sort(winners)[1]
}
```

```{r}
best('TX', 'heart attack')
```

```{r}
best("TX", "heart failure")
```
```{r}
best("MD", "heart attack")
```
```{r}
best("MD", "pneumonia")
```

```{r}
best("BB", "heart attack")
```
```{r}
best("NY", "hert attack")
```

## 3 Ranking hospitals by outcome in a state

```{r}
rankhospital <- function(state, outcome, num = "best") {
## Read outcome data
        outcome.data <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
## Check that state and outcome are valid
        try(if(!state %in% outcome.data$State) stop("invalid state"))
        outcomes <- c("heart attack", "heart failure", "pneumonia")
        try(if(!outcome %in% outcomes) stop("invalid outcome"))
## Return hospital name in that state with the given rank 30-day death rate
        # only use data of requested state
        outcome.data.state <- outcome.data[outcome.data$State == state,]
        
        # list indexes of relevent columns of outcomes
        index.list <- c("heart attack" = 11, "heart failure" = 17, "pneumonia" = 23)
        index <- index.list[outcome]
        
        # transform worded rank to numbered rank if necessary
        if (num == "best"){rank <- 1}
        if (num == "worst"){rank <-               length(na.omit(as.numeric(sort(outcome.data.state[,index]))))}
        else {rank <- num}
        
        # Transform outcome variable column to numeric
        outcome.data.state[,index] <- as.numeric(outcome.data.state[,index])
        # Find the value of outcome variable given the rank
        value <- sort(outcome.data.state[,index])[rank] 
        # Find names of hospital which have this value, omit NAs herein
        winners = na.omit(outcome.data.state[outcome.data.state[,index] == value, 2])
        # In case of ties, sorting alphabetically and return the first
        sort(winners)[1]
        
}
```

```{r}
rankhospital("TX", "heart failure", 4)
```
```{r}
rankhospital("MD", "heart attack", "worst")
```
```{r}
rankhospital("MN", "heart attack", 5000)
```

## 4 Ranking hospitals in all states

```{r}
rankall <- function(outcome, num = "best") {
## Read outcome data
        outcome.data <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
        states = sort(unique(outcome.data$State))
## Check outcome is valid
        outcomes <- c("heart attack", "heart failure", "pneumonia")
        try(if(!outcome %in% outcomes) stop("invalid outcome"))

        # list indexes of relevent columns of outcomes
        index.list <- c("heart attack" = 11, "heart failure" = 17, "pneumonia" = 23)
        index <- index.list[outcome]
        
        # transform worded rank to numbered rank if necessary
        #if (num == "best"){rank <- 1}
        #if (num == "worst"){rank <- length(na.omit(as.numeric(sort(outcome.data[,index]))))}
        #else {rank <- num}
        
## For each state, find the hospital of the given rank
outcome.data[,index] <- as.numeric(outcome.data[,index])
outcome.data <- na.omit(outcome.data, outcome.data[,index])
outcome.data <- outcome.data[order(outcome.data$State,outcome.data[,index],outcome.data$Hospital.Name),]

# Initialize empty data frame
df <- data.frame(matrix(ncol = 2, nrow = 0))
colnames(df) <- c("Hospital","State")

df_state <- data.frame(matrix(ncol = 2, nrow = 0))
colnames(df_state) <- c("Hospital","State")


for (state in states){
        outcome.data.state <- outcome.data[outcome.data$State == state,]
        
        if (num == "best"){rank <- 1}
        else if (num == "worst"){rank <-    length(na.omit(as.numeric(sort(outcome.data.state[,index]))))}
        else {rank <- num}
                
        df_state <- rbind(c(outcome.data.state[rank, 2], state))
        df <- rbind(df, df_state)
}

## Return a data frame with the hospital names and the
## (abbreviated) state name
df 
}
```

```{r}
 head(rankall("heart attack", 20), 10)
```
```{r}
tail(rankall("pneumonia", "worst"), 3)
```
```{r}
tail(rankall("heart failure"), 10)
```

